In [18]:
#7576

In [19]:
import numpy as np

In [2]:
m, n = map(int, input().split())

6 4


In [3]:
a = list(map(int, input().split()))

0 0 0 0 0 0


In [6]:
a

[0, 0, 0, 0, 0, 0]

In [7]:
#1

# 0 0 0 0 0 0
# 0 0 0 0 0 0
# 0 0 0 0 0 0
# 0 0 0 0 0 1

In [8]:
#2

# 0 0 0 0 0 0
# 0 0 0 0 0 0
# 0 0 0 0 0 1
# 0 0 0 0 1 1

In [9]:
#3

# 0 0 0 0 0 0
# 0 0 0 0 0 1
# 0 0 0 0 1 1
# 0 0 0 1 1 1

In [10]:
#4

# 0 0 0 0 0 1
# 0 0 0 0 1 1
# 0 0 0 1 1 1
# 0 0 1 1 1 1

In [12]:
#6

# 0 0 0 0 1 1
# 0 0 0 1 1 1
# 0 0 1 1 1 1
# 0 1 1 1 1 1

In [13]:
#7

# 0 0 0 1 1 1
# 0 0 1 1 1 1
# 0 1 1 1 1 1
# 1 1 1 1 1 1

In [14]:
#8

# 0 0 1 1 1 1
# 0 1 1 1 1 1
# 1 1 1 1 1 1
# 1 1 1 1 1 1

In [15]:
#9

# 0 1 1 1 1 1
# 1 1 1 1 1 1
# 1 1 1 1 1 1
# 1 1 1 1 1 1

In [16]:
#9  -> 8번 (총익는)

# 1 1 1 1 1 1
# 1 1 1 1 1 1
# 1 1 1 1 1 1
# 1 1 1 1 1 1

In [49]:
arr = np.array([[], []])

In [56]:
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [54]:
arr[0]

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [66]:
arr = np.zeros((n, m))

In [60]:
arr[0][1] = 1

In [76]:
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [75]:
arr[3][5] = 1

In [78]:
count = 0

In [77]:
while (arr == 0) == False:
    for i in range():
        for j in range():
            #arr[i][j]
            
                

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False]])

In [81]:
arr.index(1)

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [85]:
if (arr == 1) == True:
    print(arr.index(1))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [92]:
if 1 in arr:
    print(arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [100]:
arr2 = np.where(arr == 1)

In [101]:
arr2

(array([3]), array([5]))

In [105]:
arr2[1][0]

5